services:
  koalawiki:
    build:
      context: .
      dockerfile: src/KoalaWiki/Dockerfile
    #image: koala-wiki:latest
    ports:
      - "8080:8080"
    environment:
      - KOALAWIKI_REPOSITORIES=/app/repositories
      - TaskMaxSizePerUser=5
    volumes:
      - ./repositories:/app/repositories
      - ./data:/data

  koalawiki-web:
    build:
      context: web/.
      dockerfile: web/Dockerfile
    #image: koala-wiki-web:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080